<?php

declare(strict_types=1);

return [
    'delayed_status_days' => (int) env('OPERATIONS_DELAYED_STATUS_DAYS', 7),
    'marketing_unsubscribe_days' => 30,
    'system_actor_email' => 'system-seeder@localhost.invalid',
    'company_industries' => [
        'food',
        'agriculture',
        'manufacturing',
        'metal',
        'machinery',
        'electrical_electronics',
        'automotive',
        'textile',
        'plastic',
        'construction',
        'energy',
        'technology',
        'information_technology',
        'software',
        'telecommunications',
        'healthcare',
        'pharmaceuticals',
        'education',
        'finance',
        'insurance',
        'logistics',
        'tourism',
        'retail',
        'services',
        'consulting',
        'media',
        'mining',
        'chemicals',
        'packaging',
        'furniture',
        'other',
    ],
];
